version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sample
      MONGO_INITDB_ROOT_PASSWORD: sample
    ports:
      - 27017:27017
    volumes:
      - ./mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sample
      ME_CONFIG_MONGODB_ADMINPASSWORD: sample
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
